parameters:
# these are the new vars we'd need to add
- name: "sector"
  type: string
  default: ""
- name: "regions"
  type: object
  default: {}
- name: "dependsOn"
  type: object
  default: []
# we'd add the "regular" variables as we have them now for a "real" deployment (as seen in ../prod-release-tag.yml)
# - name: environment
#   type: string
#   default: ""
# - name: rpMode
#   type: string
#   default: ""
# - name: aroVersionStorageAccount
#   type: string
#   default: ""
# - name: configFileName
#   type: string
#   default: ""
# - name: azureDevOpsJSONSPN
#   type: string
#   default: ""
# - name: vsoProjectID
#   type: string
#   default: ""
# - name: azureDevOpsE2EJSONSPN
#   type: string
#   default: ""
# - name: e2eSubscription
#   type: string
#   default: ""
# - name: billingE2EPipelineName
#   type: string
#   default: ""
# - name: billingE2EBranchName
#   type: string
#   default: ""
# - name: imageTag
#   type: string
#   default: ""
# - name: rpImageAcr
#   type: string
#   default: ""

stages:
- ${{ each region in parameters.regions }}
  - stage: "${{ region }}"
    displayName: "${{ parameters.sector }}: ${{ region }}"
    dependsOn: ${{ parameters.dependsOn }}
    jobs:
    - job: "Deploy ${{ region }}"
      steps:
      - script: |
          echo "MOCK DEPLOY STARTED FOR ${{ region }}"
          echo "MOCK DEPLOY COMPLETED FOR ${{ region }}"
    - job: "E2E Test ${{ region }}"
      steps:
      - script: |
          echo "MOCK E2E STARTED FOR ${{ region }}"
          echo "MOCK E2E COMPLETED FOR ${{ region }}"
    - job: "Billing Wait For ${{ region }}"
      steps:
      - script: |
          echo "MOCK BILLING WAIT STARTED FOR ${{ region }}"
          echo "MOCK BILLING WAIT COMPLETED FOR ${{ region }}"
    - job: "Billing E2E Test ${{ region }}"
      steps:
      - script: |
          echo "MOCK BILLING E2E STARTED FOR ${{ region }}"
          echo "MOCK BILLING E2E COMPLETED FOR ${{ region }}"
